# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

FROM ubuntu:18.04

ENV PYTHONUNBUFFERED TRUE

ARG model_name
ARG add_dir
ARG requirements
ARG setup
ARG task_code

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    fakeroot \
    ca-certificates \
    dpkg-dev \
    g++ \
    python3.6-dev \
    python3-pip \
    openjdk-11-jdk \
    curl \
    vim \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.6 1
RUN cd /tmp \
    && curl -O https://bootstrap.pypa.io/get-pip.py \
    && python get-pip.py

RUN python -m pip install --no-cache-dir torchserve
RUN python -m pip install --no-cache-dir torch==1.8.1

COPY ${add_dir}/dev-docker-entrypoint.sh /usr/local/bin/dev-entrypoint.sh
RUN chmod +x /usr/local/bin/dev-entrypoint.sh

RUN mkdir -p /opt/ml/model
COPY ${add_dir}/${model_name}.mar /opt/ml/model/${model_name}.mar

RUN mkdir -p /home/model-server/ && mkdir -p /home/model-server/tmp

ENV TEMP=/home/model-server/tmp
ADD ${add_dir}/${model_name}.tar.gz /home/model-server/code
WORKDIR /home/model-server/code

RUN if [ -f requirements.txt ] && [ ${requirements} = True ]; then python -m pip install --no-cache-dir --force-reinstall -r requirements.txt; fi
RUN if [ -f setup.py ] && [ ${setup} = True ]; then python -m pip install --no-cache-dir --force-reinstall -e .; fi
RUN python -m pip install --force-reinstall git+git://github.com/facebookresearch/dynalab.git

ENV model_name=${model_name}
ENV PYTHONIOENCODING=UTF-8
COPY ${add_dir}/${task_code}.json /home/model-server/code/${task_code}.json
ENTRYPOINT /usr/local/bin/dev-entrypoint.sh ${model_name}
